solar11

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -21,7 +21,7 @@ jobs:
           java-version: '21'
           cache: maven
 
-      # Build + tests (avec retry réseau pour Maven Central
+      # Build + tests (avec retry réseau pour Maven Central)
       - name: Build and test with Maven (retry)
         working-directory: myapp
         run: |
@@ -80,9 +80,9 @@ jobs:
 
       - name: Check DockerHub secrets presence
         run: |
-          test -n "${{ secrets.username }}"    || (echo "Missing Docker username (secrets.username)" && exit 1)
-          test -n "${{ secrets.coursdevops }}" || (echo "Missing Docker token (secrets.coursdevops)" && exit 1)
-          echo " Docker secrets detected."
+          test -n "${{ secrets.username }}"    || (echo "❌ Missing Docker username (secrets.username)" && exit 1)
+          test -n "${{ secrets.coursdevops }}" || (echo "❌ Missing Docker token (secrets.coursdevops)" && exit 1)
+          echo "✅ Docker secrets detected."
 
       - name: Login to DockerHub
         uses: docker/login-action@v3
