dockerhub added v8

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -44,15 +44,15 @@ jobs:
       # Vérification des secrets (debug)
       - name: Check DockerHub secrets presence
         run: |
-          test -n "${{ secrets.brendaaudrey  }}" || (echo "❌ Missing BRENDAAUDREY_USERNAME" && exit 1)
-          test -n "${{ secrets.brendaaudrey }}" || (echo "❌ Missing BRENDAAUDREY (token)" && exit 1)
+          test -n "${{ secrets.coursdevops }}" || (echo "❌ Missing BRENDAAUDREY_USERNAME" && exit 1)
+          test -n "${{ secrets.coursdevops}}" || (echo "❌ Missing BRENDAAUDREY (token)" && exit 1)
           echo "✅ Secrets detected"
 
       - name: Login to DockerHub
         uses: docker/login-action@v3
         with:
-          username: ${{ secrets.brendaaudrey }}
-          password: ${{ secrets.brendaaudrey }}
+          username: ${{ secrets.coursdevops}}
+          password: ${{ secrets.coursdevops }}
 
       - name: Build and push backend image
         uses: docker/build-push-action@v6
@@ -60,7 +60,7 @@ jobs:
           context: ./myapp
           dockerfile: ./myapp/Dockerfile
           push: true
-          tags: ${{ secrets.BRENDAAUDREY_USERNAME }}/tp-devops-simple-api-backend:latest
+          tags: ${{ secrets.coursdevops_USERNAME }}/tp-devops-simple-api-backend:latest
 
       # Garde ou commente ces deux étapes selon ton proje
       - name: Build and push database image
@@ -69,7 +69,7 @@ jobs:
           context: ./database
           dockerfile: ./database/Dockerfile
           push: true
-          tags: ${{ secrets.BRENDAAUDREY_USERNAME }}/tp-devops-simple-api-database:latest
+          tags: ${{ secrets.coursdevops_USERNAME }}/tp-devops-simple-api-database:latest
 
       - name: Build and push httpd image
         uses: docker/build-push-action@v6
@@ -77,4 +77,4 @@ jobs:
           context: ./httpd
           dockerfile: ./httpd/Dockerfile
           push: true
-          tags: ${{ secrets.BRENDAAUDREY_USERNAME }}/tp-devops-simple-api-httpd:latest
+          tags: ${{ secrets.coursdevops_USERNAME }}/tp-devops-simple-api-httpd:latest
