solar9

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -44,9 +44,9 @@ jobs:
       # Vérification des secrets (debug)
       - name: Check DockerHub secrets presence
         run: |
-          test -n "${{ secrets.username }}" || (echo "❌ Missing BRENDAAUDREY_USERNAME" && exit 1)
-          test -n "${{ secrets.coursdevops}}" || (echo "❌ Missing BRENDAAUDREY (token)" && exit 1)
-          echo "✅ Secrets detected"
+          test -n "${{ secrets.username }}" || (echo " Missing BRENDAAUDREY_USERNAME" && exit 1)
+          test -n "${{ secrets.coursdevops}}" || (echo " Missing BRENDAAUDREY (token)" && exit 1)
+          echo " Secrets detected"
 
       - name: Login to DockerHub
         uses: docker/login-action@v3
@@ -78,3 +78,30 @@ jobs:
           dockerfile: ./httpd/Dockerfile
           push: true
           tags: ${{ secrets.username }}/tp-devops-simple-api-httpd:latest
+
+       # --- DIAGNOSTIC AVANT SONAR ---
+      - name: Check Sonar secret presence
+        run: |
+          test -n "${{ secrets.pwdsonar}}" || (echo " Missing SONAR_TOKEN (Repository secret)" && exit 1)
+          echo " SONAR_TOKEN is set."
+
+      - name: Print Java & Maven versions
+        run: |
+          java -version
+          mvn -version
+
+      # --- ANALYSE SONARCLOUD (MODE DEBUG) ---
+      - name: SonarCloud analysis (debug)
+        working-directory: myapp
+        env:
+          # Obligatoire : token SonarCloud
+          SONAR_TOKEN: ${{ secrets.pwdsonar}}
+        run: |
+          mvn -B -e -X sonar:sonar \
+            -Dsonar.projectKey=devops \
+            -Dsonar.organization=usrsonar \
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.login="$pwdsonar" \
+            -Dsonar.sources=src/main \
+            -Dsonar.tests=src/test \
+            -Dsonar.java.binaries=target/classes
